name: Test and deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test code
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run UnitTest
        run: python -m unittest discover src/test
  deploy:
    runs-on: ubuntu-latest
    name: Deploy changes with Terraform
    environment:
      name: DEV
      url: ${{ env.APIGW_URL }}
    needs: test
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKeyId }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretAccessKey }}
      AWS_DEFAULT_REGION: "ca-central-1"
      AWS_DEFAULT_OUTPUT: "json"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.7
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform plan
        run: terraform plan -no-color
      - name: Terraform apply
        run: terraform apply -auto-approve -no-color
      - name: Get API Gatewway URL
        run: echo "APIGW_URL=${$(terraform output -raw base_url):0:-18}" #>> $GITHUB_ENV
      # - name: Test deployed Lambda through API Gatewway
      #   run: >
      #     test "$(curl ${{ env.APIGW_URL }})" = "{\"Hello\": \"World\"}"
