name: Test Python code

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test code
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: run unittest
        run: python -m unittest discover src/test